/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createInitialAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product}/image": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get: operations["getProductImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shipping-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listShippingMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentPrincipal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guest-orders/{order}/register": {
        parameters: {
            query: {
                /** @description Private guest-order bearer secret returned only at checkout. */
                guest_token: components["parameters"]["GuestToken"];
            };
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerFromGuestOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setCartItemQuantity"];
        post?: never;
        delete: operations["deleteCartItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/shipping-method": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setCartShippingMethod"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mergeGuestCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["quoteCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates a checkout for either a cookie-authenticated customer or a guest. The idempotency key is scoped to that access context. */
        post: operations["createCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCustomerOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get: operations["getCustomerOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get: operations["getCustomerOrderStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guest-orders/{order}": {
        parameters: {
            query: {
                /** @description Private guest-order bearer secret returned only at checkout. */
                guest_token: components["parameters"]["GuestToken"];
            };
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get: operations["getGuestOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guest-orders/{order}/status": {
        parameters: {
            query: {
                /** @description Private guest-order bearer secret returned only at checkout. */
                guest_token: components["parameters"]["GuestToken"];
            };
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get: operations["getGuestOrderStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhooks/mock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receiveMockPaymentWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminProducts"];
        put?: never;
        post: operations["createAdminProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get: operations["getAdminProduct"];
        put: operations["replaceAdminProduct"];
        post?: never;
        delete: operations["deleteAdminProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{product}/image": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replaceAdminProductImage"];
        delete: operations["deleteAdminProductImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminCategories"];
        put?: never;
        post: operations["createAdminCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        get: operations["getAdminCategory"];
        put: operations["replaceAdminCategory"];
        post?: never;
        delete: operations["deleteAdminCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/taxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminTaxes"];
        put?: never;
        post: operations["createAdminTax"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/taxes/{tax}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tax: components["parameters"]["TaxId"];
            };
            cookie?: never;
        };
        get: operations["getAdminTax"];
        put: operations["replaceAdminTax"];
        post?: never;
        delete: operations["deleteAdminTax"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/shipping-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminShippingMethods"];
        put?: never;
        post: operations["createAdminShippingMethod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/shipping-methods/{shippingMethod}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shippingMethod: components["parameters"]["ShippingMethodId"];
            };
            cookie?: never;
        };
        get: operations["getAdminShippingMethod"];
        put: operations["replaceAdminShippingMethod"];
        post?: never;
        delete: operations["deleteAdminShippingMethod"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{product}/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get: operations["getAdminProductInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{product}/inventory-adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get: operations["listAdminInventoryAdjustments"];
        put?: never;
        post: operations["createAdminInventoryAdjustment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/product-imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Processes a bounded CSV synchronously. File-level failures reject the import; valid rows commit independently and invalid rows are retained as sanitized rejections. Numeric fields trim surrounding whitespace and accept ungrouped digits or standard thousands commas (first group 1–3 digits, subsequent groups exactly three digits). CSV cells containing commas must be quoted. Price accepts integers or 1–2 decimal places and one optional leading dollar sign with optional whitespace after it (12, 12.5, $ 12.50, "$1,234.56"). Weight_kg accepts integers or 1–4 decimal places (2, 2.5000, "1,234.5678"). Stock accepts integers only (0, 12, "1,000"). Weight_kg and stock do not accept dollar signs. Normalized values are persisted without currency symbols or grouping separators, without rounding or truncation. Values must be non-negative and within database ranges (price at most 999999999999999.9999, weight_kg at most 99999999.9999, stock at most 4294967295). When stock is written, its audit adjustment delta must fit -2147483648 to 2147483647; new-product stock is therefore at most 2147483647. Larger changes also reject the row with Invalid stock value. Empty values, signs, negatives, exponents, decimal commas, NaN, Infinity, malformed grouping, excess decimal places, and out-of-range values reject only their row with the exact reasons Invalid price value, Invalid weight_kg value, or Invalid stock value. Every applicable numeric reason appears once in the rejection CSV. Numeric validation applies even when CSV stock is ignored for existing products. */
        post: operations["createAdminProductImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/product-imports/{import}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        get: operations["getAdminProductImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/product-imports/{import}/rejections.csv": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        get: operations["downloadAdminProductImportRejections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/orders/{order}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get: operations["getAdminOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/manual-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminManualReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/manual-reviews/{review}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveAdminManualReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["SettingKey"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setAdminSetting"];
        post?: never;
        delete: operations["deleteAdminSettingOverride"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example 01K6H2B57Y9X2A1B3C4D5E6F7G */
        Ulid: string;
        /** @example 19.99 */
        MoneyAmount: string;
        /** @example 19.99 */
        MoneyInput: string;
        /** @example 1.2500 */
        WeightKilograms: string;
        /** @example 1.25 */
        WeightKilogramsInput: string;
        /** @example USD */
        CurrencyCode: string;
        /**
         * Format: date-time
         * @example 2026-10-04T15:30:00Z
         */
        UtcTimestamp: string;
        Version: number;
        Pagination: {
            page: number;
            /** @enum {integer} */
            per_page: 10 | 20 | 50 | 100;
            total: number;
            total_pages: number;
        };
        ProblemFields: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail: string;
            /** Format: uri-reference */
            instance?: string;
            code: string;
            errors?: {
                [key: string]: string[];
            };
        };
        ProblemDetails: components["schemas"]["ProblemFields"];
        TaxDeleteProblem: components["schemas"]["ProblemFields"] & {
            active_product_references?: number;
            active_shipping_method_references?: number;
        };
        ImportProblem: components["schemas"]["ProblemFields"] & {
            row_errors?: components["schemas"]["ImportRejection"][];
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            service: string;
        };
        Address: {
            name: string;
            line1: string;
            line2?: string;
            city: string;
            region: string;
            postal_code: string;
            country: string;
            phone: string;
        };
        SetupAdminInput: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        RegistrationInput: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            address: components["schemas"]["Address"];
        };
        Principal: {
            id: components["schemas"]["Ulid"];
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "customer";
        };
        Category: {
            id: components["schemas"]["Ulid"];
            name: string;
            slug: string;
            active: boolean;
            version: components["schemas"]["Version"];
        };
        CategoryInput: {
            name: string;
            slug: string;
            active: boolean;
        };
        Tax: {
            id: components["schemas"]["Ulid"];
            name: string;
            rate: string;
            active: boolean;
            version: components["schemas"]["Version"];
        };
        TaxInput: {
            name: string;
            rate: string;
            active: boolean;
        };
        ShippingMethod: {
            id: components["schemas"]["Ulid"];
            name: string;
            amount: components["schemas"]["MoneyAmount"];
            currency: components["schemas"]["CurrencyCode"];
            active: boolean;
            version: components["schemas"]["Version"];
        };
        ShippingMethodInput: {
            name: string;
            amount: components["schemas"]["MoneyAmount"];
            currency: components["schemas"]["CurrencyCode"];
            tax_id: components["schemas"]["Ulid"];
            active: boolean;
        };
        Product: {
            id: components["schemas"]["Ulid"];
            sku: string;
            name: string;
            description: string;
            price: components["schemas"]["MoneyAmount"];
            weight_kg: components["schemas"]["WeightKilograms"];
            /**
             * @description Confirms that price is the base unit price before tax.
             * @constant
             */
            price_excludes_tax: true;
            currency: components["schemas"]["CurrencyCode"];
            /** @description Active category metadata, or null for the virtual Uncategorized grouping. */
            category: components["schemas"]["Category"] | null;
            /** @description Active tax identifier used when calculating checkout totals, or null when no tax applies. */
            tax_id: components["schemas"]["Ulid"] | null;
            /** Format: uri-reference */
            image_url: string;
            in_stock: boolean;
            version: components["schemas"]["Version"];
            created_at: components["schemas"]["UtcTimestamp"];
            updated_at: components["schemas"]["UtcTimestamp"];
        };
        ProductInput: {
            sku: string;
            name: string;
            description: string;
            price: components["schemas"]["MoneyInput"];
            weight_kg: components["schemas"]["WeightKilogramsInput"];
            currency: components["schemas"]["CurrencyCode"];
            category_id: components["schemas"]["Ulid"];
            tax_id: components["schemas"]["Ulid"];
            active: boolean;
            initial_on_hand?: number;
        };
        ProductPage: {
            items: components["schemas"]["Product"][];
            pagination: components["schemas"]["Pagination"];
        };
        CartLineInput: {
            product_id: components["schemas"]["Ulid"];
            quantity: number;
        };
        CartLine: {
            product_id: components["schemas"]["Ulid"];
            name: string;
            quantity: number;
            unit_price: components["schemas"]["MoneyAmount"];
            line_subtotal: components["schemas"]["MoneyAmount"];
            currency: components["schemas"]["CurrencyCode"];
            available: boolean;
            stock_limit?: number;
            adjustment?: string;
        };
        Cart: {
            lines: components["schemas"]["CartLine"][];
            subtotal: components["schemas"]["MoneyAmount"];
            /** @description Sum of independently rounded product-line taxes; zero when no products are taxable. */
            product_tax: components["schemas"]["MoneyAmount"];
            /** @description Independently rounded shipping tax; zero when shipping has no tax assignment. */
            shipping_tax: components["schemas"]["MoneyAmount"];
            /** @description Backward-compatible aggregate equal to product_tax plus shipping_tax. */
            tax: components["schemas"]["MoneyAmount"];
            shipping: components["schemas"]["MoneyAmount"];
            total: components["schemas"]["MoneyAmount"];
            currency: components["schemas"]["CurrencyCode"];
            requires_confirmation: boolean;
        };
        CheckoutInput: {
            /** Format: email */
            email: string;
            shipping_address: components["schemas"]["Address"];
            shipping_method_id: components["schemas"]["Ulid"];
            lines: components["schemas"]["CartLineInput"][];
            /** @enum {string} */
            payment_test_number: "4000000000010001" | "4000000000000002" | "4000000000090003" | "4000000000080004";
        };
        CheckoutResult: {
            order: components["schemas"]["Order"];
            guest: boolean;
            /**
             * Format: uri-reference
             * @description Returned exactly once for guest checkout.
             */
            guest_order_url?: string;
        };
        /** @enum {string} */
        OrderStatus: "awaiting_payment" | "paid" | "payment_failed" | "expired" | "manual_review" | "review_processed";
        /** @enum {string} */
        PaymentStatus: "pending" | "succeeded" | "declined" | "error" | "manual_review";
        OrderStatusView: {
            order_id: components["schemas"]["Ulid"];
            status: components["schemas"]["OrderStatus"];
            payment_status: components["schemas"]["PaymentStatus"];
            updated_at: components["schemas"]["UtcTimestamp"];
        };
        Order: {
            id: components["schemas"]["Ulid"];
            number: string;
            status: components["schemas"]["OrderStatus"];
            payment_status: components["schemas"]["PaymentStatus"];
            lines: components["schemas"]["CartLine"][];
            total: components["schemas"]["MoneyAmount"];
            currency: components["schemas"]["CurrencyCode"];
            shipping_address: components["schemas"]["Address"];
            version: components["schemas"]["Version"];
            created_at: components["schemas"]["UtcTimestamp"];
            updated_at: components["schemas"]["UtcTimestamp"];
            state_history?: {
                [key: string]: unknown;
            }[];
            reservations?: {
                [key: string]: unknown;
            }[];
            payment?: {
                [key: string]: unknown;
            } | null;
            manual_review?: {
                [key: string]: unknown;
            } | null;
            /** Format: email */
            customer_email?: string;
            shipping_method_name?: string;
            amounts?: {
                subtotal: components["schemas"]["MoneyAmount"];
                product_tax: components["schemas"]["MoneyAmount"];
                shipping: components["schemas"]["MoneyAmount"];
                shipping_tax: components["schemas"]["MoneyAmount"];
                total: components["schemas"]["MoneyAmount"];
                currency: components["schemas"]["CurrencyCode"];
            };
        };
        OrderPage: {
            items: components["schemas"]["Order"][];
            pagination: components["schemas"]["Pagination"];
        };
        PaymentWebhookInput: {
            event_id: components["schemas"]["Ulid"];
            commerce_payment_id: components["schemas"]["Ulid"];
            provider_payment_id: components["schemas"]["Ulid"];
            /** @enum {string} */
            outcome: "succeeded" | "declined" | "error";
            provider_code: string;
            occurred_at: components["schemas"]["UtcTimestamp"];
        };
        Inventory: {
            product_id: components["schemas"]["Ulid"];
            on_hand: number;
            reserved: number;
            available: number;
        };
        InventoryAdjustment: {
            id: components["schemas"]["Ulid"];
            product_id: components["schemas"]["Ulid"];
            previous_on_hand: number;
            new_on_hand: number;
            reason: string;
            note?: string;
            actor_id: components["schemas"]["Ulid"];
            created_at: components["schemas"]["UtcTimestamp"];
        };
        InventoryAdjustmentPage: {
            items: components["schemas"]["InventoryAdjustment"][];
            pagination: components["schemas"]["Pagination"];
        };
        ImportRejection: {
            row: number;
            sku?: string;
            reason: string;
        };
        ProductImport: {
            id: components["schemas"]["Ulid"];
            /** @enum {string} */
            status: "completed" | "completed_with_rejections" | "failed";
            original_filename: string;
            /** @enum {string} */
            mode: "create_only" | "update_only" | "upsert";
            /**
             * @description create creates every missing category encountered in valid rows; reject rejects unknown categories; uncategorized imports without a category and records a warning.
             * @enum {string}
             */
            unknown_category_policy: "reject" | "create" | "uncategorized";
            stock_override: boolean;
            stock_override_confirmed_at: components["schemas"]["UtcTimestamp"] | null;
            total_rows: number;
            accepted_rows: number;
            warning_rows: number;
            rejected_rows: number;
            created_at: components["schemas"]["UtcTimestamp"];
            updated_at: components["schemas"]["UtcTimestamp"];
        };
        Setting: {
            /** @enum {string} */
            key: "reservation_timeout_seconds";
            value: number;
            /** @enum {string} */
            source: "environment" | "database";
        };
        AuditLog: {
            id: components["schemas"]["Ulid"];
            actor_id: components["schemas"]["Ulid"];
            action: string;
            subject_type: string;
            subject_id: components["schemas"]["Ulid"];
            metadata?: {
                [key: string]: unknown;
            };
            created_at: components["schemas"]["UtcTimestamp"];
        };
        AuditLogPage: {
            items: components["schemas"]["AuditLog"][];
            pagination: components["schemas"]["Pagination"];
        };
    };
    responses: {
        /** @description Healthy */
        Health: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Health"];
            };
        };
        /** @description Product */
        Product: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Product"];
            };
        };
        /** @description Paginated products */
        ProductPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProductPage"];
            };
        };
        /** @description Category */
        Category: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Category"];
            };
        };
        /** @description Categories */
        CategoryList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Category"][];
            };
        };
        /** @description Shipping method */
        ShippingMethod: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ShippingMethod"];
            };
        };
        /** @description Shipping methods */
        ShippingMethodList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ShippingMethod"][];
            };
        };
        /** @description Tax */
        Tax: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Tax"];
            };
        };
        /** @description Taxes */
        TaxList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Tax"][];
            };
        };
        /** @description Authenticated principal */
        Principal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Principal"];
            };
        };
        /** @description Revalidated cart and totals */
        Cart: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Cart"];
            };
        };
        /** @description Order detail */
        Order: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Order"];
            };
        };
        /** @description Paginated orders */
        OrderPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OrderPage"];
            };
        };
        /** @description Current order and payment status */
        OrderStatus: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OrderStatusView"];
            };
        };
        /** @description Inventory quantities */
        Inventory: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Inventory"];
            };
        };
        /** @description Paginated inventory adjustments */
        InventoryAdjustmentPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["InventoryAdjustmentPage"];
            };
        };
        /** @description Import result and row counts */
        ProductImport: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProductImport"];
            };
        };
        /** @description Effective setting */
        Setting: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Setting"];
            };
        };
        /** @description Allowlisted settings */
        SettingList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Setting"][];
            };
        };
        /** @description Paginated audit events */
        AuditLogPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuditLogPage"];
            };
        };
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description File-level or row-level validation failed */
        ImportValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ImportProblem"];
            };
        };
        /** @description Malformed request */
        Problem400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authentication required or invalid */
        Problem401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated principal lacks permission */
        Problem403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource not found or not owned */
        Problem404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description State, idempotency, or optimistic-concurrency conflict */
        Problem409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request exceeds configured byte limit */
        Problem413: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unsupported request media type */
        Problem415: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Request validation failed */
        Problem422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Rate limit exceeded */
        Problem429: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unexpected server error */
        Problem500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Required dependency unavailable */
        Problem503: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        ProductId: components["schemas"]["Ulid"];
        CategoryId: components["schemas"]["Ulid"];
        TaxId: components["schemas"]["Ulid"];
        ShippingMethodId: components["schemas"]["Ulid"];
        OrderId: components["schemas"]["Ulid"];
        ImportId: components["schemas"]["Ulid"];
        ReviewId: components["schemas"]["Ulid"];
        SettingKey: "reservation_timeout_seconds";
        /** @description Private guest-order bearer secret returned only at checkout. */
        GuestToken: string;
        IdempotencyKey: string;
        /** @description Expected current resource version for optimistic concurrency. */
        ExpectedVersion: number;
        Search: string;
        CategoryFilter: components["schemas"]["Ulid"];
        MinPrice: components["schemas"]["MoneyAmount"];
        MaxPrice: components["schemas"]["MoneyAmount"];
        InStock: boolean;
        ProductSort: "name" | "price" | "created_at";
        SortDirection: "asc" | "desc";
        DeletedFilter: "exclude" | "include" | "only";
        OrderStatusFilter: components["schemas"]["OrderStatus"];
        PaymentStateFilter: "requested" | "processing" | "initiation_failed" | "succeeded" | "declined" | "provider_error";
        CustomerEmailFilter: string;
        OrderNumberFilter: string;
        /** @description Actor ULID or exact email address. */
        AuditActorFilter: string;
        AuditActionFilter: string;
        /** @description Exact target ULID or partial target type. */
        AuditTargetFilter: string;
        DateFrom: string;
        DateTo: string;
        Page: number;
        PerPage: 10 | 20 | 50 | 100;
    };
    requestBodies: {
        Login: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        SetupAdmin: {
            content: {
                "application/json": components["schemas"]["SetupAdminInput"];
            };
        };
        Register: {
            content: {
                "application/json": components["schemas"]["RegistrationInput"];
            };
        };
        GuestRegistration: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        CartQuantity: {
            content: {
                "application/json": {
                    quantity: number;
                };
            };
        };
        ShippingSelection: {
            content: {
                "application/json": {
                    shipping_method_id: components["schemas"]["Ulid"] | null;
                };
            };
        };
        CartLines: {
            content: {
                "application/json": {
                    lines: components["schemas"]["CartLineInput"][];
                };
            };
        };
        CartQuote: {
            content: {
                "application/json": {
                    lines: components["schemas"]["CartLineInput"][];
                    shipping_method_id?: components["schemas"]["Ulid"] | null;
                };
            };
        };
        Checkout: {
            content: {
                "application/json": components["schemas"]["CheckoutInput"];
            };
        };
        PaymentWebhook: {
            content: {
                "application/json": components["schemas"]["PaymentWebhookInput"];
            };
        };
        ProductMutation: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        CategoryMutation: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        TaxMutation: {
            content: {
                "application/json": components["schemas"]["TaxInput"];
            };
        };
        ShippingMethodMutation: {
            content: {
                "application/json": components["schemas"]["ShippingMethodInput"];
            };
        };
        ProductImage: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description JPEG, PNG, or WebP image within the configured byte limit.
                     */
                    image: string;
                };
            };
        };
        InventoryAdjustment: {
            content: {
                "application/json": {
                    on_hand: number;
                    reason: string;
                    note?: string;
                };
            };
        };
        ProductImport: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @enum {string} */
                    mode: "create_only" | "update_only" | "upsert";
                    /**
                     * @description create creates every missing category encountered in valid rows; reject rejects unknown categories; uncategorized imports without a category and records a warning.
                     * @enum {string}
                     */
                    unknown_category_policy: "reject" | "create" | "uncategorized";
                    override_stock: boolean;
                    /** @description Must be true when override_stock is true. */
                    confirm_stock_override?: boolean;
                };
            };
        };
        ReviewResolution: {
            content: {
                "application/json": {
                    note: string;
                    version: number;
                };
            };
        };
        SettingMutation: {
            content: {
                "application/json": {
                    value: number;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
            500: components["responses"]["InternalError"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        available: boolean;
                    };
                };
            };
        };
    };
    createInitialAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SetupAdmin"];
        responses: {
            201: components["responses"]["Principal"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                q?: components["parameters"]["Search"];
                category?: components["parameters"]["CategoryFilter"];
                min_price?: components["parameters"]["MinPrice"];
                max_price?: components["parameters"]["MaxPrice"];
                in_stock?: components["parameters"]["InStock"];
                sort?: components["parameters"]["ProductSort"];
                direction?: components["parameters"]["SortDirection"];
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProductPage"];
            400: components["responses"]["BadRequest"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Product"];
            404: components["responses"]["NotFound"];
        };
    };
    getProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uploaded product image or the SVG placeholder */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    "X-Content-Type-Options"?: "nosniff";
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                    "image/svg+xml": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CategoryList"];
        };
    };
    listShippingMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ShippingMethodList"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Login"];
        responses: {
            200: components["responses"]["Principal"];
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getCurrentPrincipal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Principal"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    registerCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Register"];
        responses: {
            201: components["responses"]["Principal"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    registerFromGuestOrder: {
        parameters: {
            query: {
                /** @description Private guest-order bearer secret returned only at checkout. */
                guest_token: components["parameters"]["GuestToken"];
            };
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GuestRegistration"];
        responses: {
            201: components["responses"]["Principal"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Cart"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    setCartItemQuantity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CartQuantity"];
        responses: {
            200: components["responses"]["Cart"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Cart"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setCartShippingMethod: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ShippingSelection"];
        responses: {
            200: components["responses"]["Cart"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    mergeGuestCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CartLines"];
        responses: {
            200: components["responses"]["Cart"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    quoteCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CartQuote"];
        responses: {
            200: components["responses"]["Cart"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createCheckout: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Checkout"];
        responses: {
            /** @description Payment accepted for asynchronous processing */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResult"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listCustomerOrders: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OrderPage"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getCustomerOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Order"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    getCustomerOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OrderStatus"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    getGuestOrder: {
        parameters: {
            query: {
                /** @description Private guest-order bearer secret returned only at checkout. */
                guest_token: components["parameters"]["GuestToken"];
            };
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Order"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getGuestOrderStatus: {
        parameters: {
            query: {
                /** @description Private guest-order bearer secret returned only at checkout. */
                guest_token: components["parameters"]["GuestToken"];
            };
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OrderStatus"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    receiveMockPaymentWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PaymentWebhook"];
        responses: {
            /** @description Event accepted or already processed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listAdminProducts: {
        parameters: {
            query?: {
                q?: components["parameters"]["Search"];
                deleted?: components["parameters"]["DeletedFilter"];
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProductPage"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ProductMutation"];
        responses: {
            201: components["responses"]["Product"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getAdminProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Product"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceAdminProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected current resource version for optimistic concurrency. */
                "If-Match-Version": components["parameters"]["ExpectedVersion"];
            };
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ProductMutation"];
        responses: {
            200: components["responses"]["Product"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteAdminProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected current resource version for optimistic concurrency. */
                "If-Match-Version": components["parameters"]["ExpectedVersion"];
            };
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted or deactivated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    replaceAdminProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ProductImage"];
        responses: {
            200: components["responses"]["Product"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteAdminProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Product"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CategoryList"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CategoryMutation"];
        responses: {
            201: components["responses"]["Category"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getAdminCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Category"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceAdminCategory: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected current resource version for optimistic concurrency. */
                "If-Match-Version": components["parameters"]["ExpectedVersion"];
            };
            path: {
                category: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CategoryMutation"];
        responses: {
            200: components["responses"]["Category"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteAdminCategory: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected current resource version for optimistic concurrency. */
                "If-Match-Version": components["parameters"]["ExpectedVersion"];
            };
            path: {
                category: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category soft-deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listAdminTaxes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TaxList"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminTax: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TaxMutation"];
        responses: {
            201: components["responses"]["Tax"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getAdminTax: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tax: components["parameters"]["TaxId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Tax"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceAdminTax: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected current resource version for optimistic concurrency. */
                "If-Match-Version": components["parameters"]["ExpectedVersion"];
            };
            path: {
                tax: components["parameters"]["TaxId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TaxMutation"];
        responses: {
            200: components["responses"]["Tax"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteAdminTax: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected current resource version for optimistic concurrency. */
                "If-Match-Version": components["parameters"]["ExpectedVersion"];
            };
            path: {
                tax: components["parameters"]["TaxId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tax soft-deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Stale version or active references prevent deletion */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["TaxDeleteProblem"];
                };
            };
        };
    };
    listAdminShippingMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ShippingMethodList"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminShippingMethod: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ShippingMethodMutation"];
        responses: {
            201: components["responses"]["ShippingMethod"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getAdminShippingMethod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shippingMethod: components["parameters"]["ShippingMethodId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ShippingMethod"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceAdminShippingMethod: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected current resource version for optimistic concurrency. */
                "If-Match-Version": components["parameters"]["ExpectedVersion"];
            };
            path: {
                shippingMethod: components["parameters"]["ShippingMethodId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ShippingMethodMutation"];
        responses: {
            200: components["responses"]["ShippingMethod"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteAdminShippingMethod: {
        parameters: {
            query?: never;
            header: {
                /** @description Expected current resource version for optimistic concurrency. */
                "If-Match-Version": components["parameters"]["ExpectedVersion"];
            };
            path: {
                shippingMethod: components["parameters"]["ShippingMethodId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shipping method soft-deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getAdminProductInventory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Inventory"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminInventoryAdjustments: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["InventoryAdjustmentPage"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createAdminInventoryAdjustment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["InventoryAdjustment"];
        responses: {
            201: components["responses"]["Inventory"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    createAdminProductImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ProductImport"];
        responses: {
            200: components["responses"]["ProductImport"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ImportValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getAdminProductImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProductImport"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadAdminProductImportRejections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanitized rejected rows with a reason column */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminOrders: {
        parameters: {
            query?: {
                status?: components["parameters"]["OrderStatusFilter"];
                payment_status?: components["parameters"]["PaymentStateFilter"];
                date_from?: components["parameters"]["DateFrom"];
                date_to?: components["parameters"]["DateTo"];
                email?: components["parameters"]["CustomerEmailFilter"];
                number?: components["parameters"]["OrderNumberFilter"];
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OrderPage"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Order"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminManualReviews: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OrderPage"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    resolveAdminManualReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review: components["parameters"]["ReviewId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ReviewResolution"];
        responses: {
            200: components["responses"]["Order"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SettingList"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    setAdminSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["SettingKey"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SettingMutation"];
        responses: {
            200: components["responses"]["Setting"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteAdminSettingOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["SettingKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Setting"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminAuditLogs: {
        parameters: {
            query?: {
                q?: components["parameters"]["Search"];
                /** @description Actor ULID or exact email address. */
                actor?: components["parameters"]["AuditActorFilter"];
                action?: components["parameters"]["AuditActionFilter"];
                /** @description Exact target ULID or partial target type. */
                target?: components["parameters"]["AuditTargetFilter"];
                date_from?: components["parameters"]["DateFrom"];
                date_to?: components["parameters"]["DateTo"];
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AuditLogPage"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
}
